name: GiveMeABreak
options:
  bundleIdPrefix: com.givemeabreak
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  GiveMeABreak:
    type: application
    platform: macOS
    sources:
      - path: GiveMeABreak
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.givemeabreak.app
        PRODUCT_NAME: Give Me A Break
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: GiveMeABreak/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: NO
